### ISSUE TITLE
No useful README?

### ISSUE THREAD

**Issue by binyamin555** [Adevien/Replica#1]
I couldn't have not noticed the project's missing a useful README. The current one is just a dancing dog.

I think it would be much better to add a README that explains 
 * What this project is about.
 * How to use it.
 * What are the requirements.
 * How to contribute (if any)
 
 Thank you in advance :D

**Comment by binyamin555** [comment]
I guess it's still WIP? Please don't close the issue before it's resolved :)

**Comment by Adevien** [comment]
What this project is about. 
- Its a hobby project of mine with the goal of creating a framework for network replication using eventual consistency, aimed for game, in the beginning i'm not sure its best way to go, but for now this should suffice.
How to use it.
- There will be demos and documentation but for now the project is not even in a state of functionality that would allow testing outside the networked properties.
What are the requirements.
- No requirements yes other than Mono.Cecil but since this is made with Unity in mind , and unity already has a package version of it we'll use that.
How to contribute (if any)
- For now there isn't much to contribute to until the whole design is layered out properly.

**Comment by binyamin555** [comment]
great! now all you need is to write it in the README instead of here

**Comment by Adevien** [comment]
Go for it.
